### RunEventGenerator.mac

# $Id:For running with or without visualization
# on the RP-GEn simulation 4/11/2019 $
# 
# This macro feeds commands to the primary event generator and allows 
# for changing of beam parameters within the macro. 
#
# can be run in batch, without graphic
# or interactively: Idle> /control/execute RunEventGenerator.mac

#/vis/viewer/set/viewpointThetaPhi -45 180 deg
#/vis/viewer/zoom 1.5

/run/initialize
/run/verbose 0
/event/verbose 0
/material/verbose 0
/cuts/verbose 0
/process/verbose 0

/tracking/verbose 0
/tracking/storeTrajectory 1

### Particle Gun Commands ####
# Particle type
/gun/particle neutron

#
# Commands below are for the NPOL messenger
#
/npol/polarScattering true  # turn off(false) or on(true) 
					  		# Glasgow polarized scattering
							
/npol/gun/maxDCS 0.045
/npol/gun/filter polarized
/npol/gun/generator dcs
/npol/gun/channel 3
/npol/gun/energy 4.4 GeV
/npol/gun/beamPolarization 0.80
/npol/gun/openAngle 25.0 
/npol/gun/helicityRatio 1.0
/npol/gun/GEn 0.0			# a value of '0' triggers built
/npol/gun/GMn 0.0			# in computation of GEn and GMn  
		

#
# Run commands
#
/vis/scene/endOfEventAction accumulate 200
/run/printProgress 100
/run/beamOn 2000
